name: "Version"

on:
  push:
    branches:
      - "master"
    paths:
      - "**/*.tsx"
      - "**/*.ts"
      - "**/*.jsx"
      - "**/*.js"
      - "*.json"

env:
  DOCKER_BUILDKIT: 1

jobs:
  bump-version:
    name: "Bump Version on master"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://npm.pkg.github.com"
          scope: "@shipeedo"

      - name: "cat package.json"
        run: cat ./package.json

      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: 12

      - name: Get new version
        id: get_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true

      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update package.json
        run: |
          git config --global user.email "${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"
          git config --global user.name "${{ env.GIT_COMMIT_AUTHOR_NAME }}"
          npm version ${{ steps.get_version.outputs.release_type }} -m "ci: bump version to ${{ steps.get_version.outputs.new_tag }}"
          git push origin master

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
